image: blang/latex:latest

# Compile LaTeX document, and release to GitLab pages
pages:
  stage: deploy
  script:
    # Upgrade system, install Ubuntu font
    - apt-get update -yqq
    - apt-get install ttf-ubuntu-font-family -yqq

    # Compile LaTeX document
    - make
    - make

    # Release
    - mkdir public
    - cp ./cv.pdf ./public/
  artifacts:
    paths:
      - public
  only:
    - master
