image: rust:latest

# Compile LaTeX document, and release to GitLab pages
pages:
  stage: deploy
  script:
    # Prepare system
    - "sed -i 's/ main/ main contrib non-free/' /etc/apt/sources.list"
    - apt-get update -yqq
    - apt-get install -yqq libfontconfig1-dev libgraphite2-dev libharfbuzz-dev libicu-dev zlib1g-dev ttf-ubuntu-font-family biber

    # Install tectonic
    - cargo install tectonic --force

    # Compile LaTeX document
    - tectonic cv.tex

    # Release
    - mkdir public
    - cp ./cv.pdf ./public/
  artifacts:
    paths:
      - public
  #only:
  #  - master
