image: ubuntu

# Compile LaTeX document, and release to GitLab pages
pages:
  stage: deploy
  script:
    # Prepare system
    - apt-get update
    - apt-get install -yq wget tar biber fonts-ubuntu

    # Install tectonic
    - wget "https://github.com/tectonic-typesetting/tectonic/releases/download/tectonic%400.12.0/tectonic-0.12.0-x86_64-unknown-linux-musl.tar.gz" -O tectonic.tar.gz
    - tar -xzvf tectonic.tar.gz

    # Compile LaTeX document
    - ./tectonic cv.tex

    # Release
    - mkdir public
    - cp ./cv.pdf ./public/
  artifacts:
    paths:
      - public
  #only:
  #  - master
